apiVersion: batch/v1
kind: CronJob
metadata:
  name: order-mgmt-svc-test
spec:
  jobTemplate:
    metadata:
      name: order-mgmt-svc-test
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      template:
        metadata:
        spec:
          containers:
          - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: Always
            name: order-mgmt-svc-test
            command:
              - "/bin/sh"
              - "-c"
              - "java -jar api-integration-tests.jar ordermanagement.xml"
            resources: {}
          restartPolicy: Never
          imagePullSecrets:
          - name: pull-image-secret
  schedule: 0 0 1 1 *
status: {}
