name: Build,Push and Deploy in K8s

on:
  workflow_call:
    inputs:
      ENV_VARIABLES_PATH:
        required: true
        type: string

    secrets:
      AZURE_CREDENTIALS:
        required: true
      GHCR_LOGIN_PWD:
        required: true
      GHCR_READ_IMG_TOKEN:
        required: true

jobs:
  deployToK8s:
    permissions:
      security-events: write
      contents: read
      id-token: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      #Checks out the repository this file is in
      - uses: actions/checkout@v3

      - name: Set Environment Variables
        uses: ./.github/actions/setvars
        with:
          varFilePath: ${{ inputs.ENV_VARIABLES_PATH }}

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_LOGIN_PWD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }} , ghcr.io/${{ github.repository }}:latest