name: Build and Deploy (dev)

on:
  push:
    branches:
      - develop
      - develop-01

jobs:
  deployToK8s:
    uses: ./.github/workflows/callable-build-job.yaml
    with:
      ENV_VARIABLES_PATH: ".github/variables/dev.env"
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS_1 }}
      GHCR_LOGIN_PWD: ${{ secrets.GITHUB_TOKEN }}
      GHCR_READ_IMG_TOKEN: ${{ secrets.GIT_TOKEN }}